### ISSUE TITLE
diff_againstパラメータを付与して複数回実行した場合にdiffの結果が毎回変化する。

### ISSUE THREAD

**Issue by sakai00kou** [yamaha-network/ansible-collection-rtx#3]
# 問題内容
`diff_against`パラメータを付与したPlaybookを`--diff`オプションをつけて複数回実行すると実行のたびにdiffの出力結果が変化する。
その際、設定が変更されない処理であっても実行結果が**changed**と判定される。

また、`diff_against`パラメータを記載しなかった場合も複数回実行すると、`diff_against`パラメータを付与した場合と比べると頻度は低いがたまに**changed**と判定される場合がある。

# 再現手順
1. 上記「実行コード」のタスクを記載したPlaybook作成。（hosts、vars設定は[公式ページ](http://www.rtpro.yamaha.co.jp/RT/docs/ansible/index.html)通り）
2. `ansible-playbook -i inventory rtx.yml`を複数回実行

# 発生頻度
- `diff_against`パラメータ付与時
5回に3回程度

- `diff_against`パラメータ無し
10回に1回程度

# 環境
- 管理サーバ
CentOS Linux release 8.3.2011
Python 3.6.8
ansible 2.10.7
yamaha_network.rtx 1.0.0

- 管理対象機器
NVR500 Rev.11.00.38

# 実行コード
以下コードで実行しました。

- Playbook
```
---
- hosts: NVR500
  connection: network_cli

  tasks:
    - name: set description
      yamaha_network.rtx.rtx_config:
        diff_against: running
        lines:
          - description 1 yamaha

  vars:
    ansible_network_os: yamaha_network.rtx.rtx
    ansible_user: user
    ansible_ssh_pass: userpass
    ansible_become: true
    ansible_become_password: becomepass
```

- Inventory
```
[YAMAHA]
NVR500 ansible_host=192.168.0.1
```
