### ISSUE TITLE
diff_againstのintendedオプション設定時の動作について

### ISSUE THREAD

**Issue by sakai00kou** [yamaha-network/ansible-collection-rtx#5]
# 問題内容
`backup`パラメータで取得したコンフィグを`intended_config`で指定し、`diff_against`パラメータを`intended`オプションで動作させた際、`--diff`オプション無しで実行した場合は実行結果が**ok**となるが、`--diff`オプションをつけて実行すると、**changed**と判定される。

また、`diff_against`パラメータを`intended`、`intended_config`と`running_config`パラメータに同じファイルを指定して実行した場合、変更点が無くても**changed**と判定される。

# 再現手順
1. 下記「実行コード」のタスクを記載したPlaybook作成。（hosts、vars設定は[公式ページ](http://www.rtpro.yamaha.co.jp/RT/docs/ansible/index.html)通り）
2. `ansible-playbook -i inventory rtx.yml`を実行

# 発生頻度
毎回

# 環境
- 管理サーバ
CentOS Linux release 8.3.2011
Python 3.6.8
ansible 2.10.7
ansible.netcommon 2.0.1
yamaha_network.rtx 1.0.1

- 管理対象機器
NVR500 Rev.11.00.38

# 実行コード
以下コードで実行しました。

- Playbook
```
---
- hosts: NVR500
  connection: network_cli

  tasks:
    - name: get configuration
      rtx_config:
        lines:
        - description 1 yamaha
        diff_against: intended
#        running_config: /root/yamaha.cfg
        intended_config: /root/yamaha.cfg
        match: line
        save_when: changed

  vars:
    ansible_network_os: yamaha_network.rtx.rtx
    ansible_user: user
    ansible_ssh_pass: userpass
    ansible_become: true
    ansible_become_password: becomepass
```

- Inventory
```
[YAMAHA]
NVR500 ansible_host=192.168.0.1
```

# 実行結果抜粋（上述の実行コードで実行）
```
# ansible-playbook -i inventory rtx.yml --diff

PLAY [NVR500] *******************************************************************************

TASK [get configuration] ********************************************************************
--- before
+++ after
@@ -1 +1,309 @@
-/root/yamaha.cfg
\ No newline at end of file
+description 1 yamaha
+login password *
+administrator password *
（省略）
+onfs bind usb1
\ No newline at end of file

changed: [NVR500]

PLAY RECAP **********************************************************************************
NVR500                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

# 補足
`running_config`パラメータが比較元となるファイルの指定、`intended_config`パラメータが比較先となるファイルを指定するパラメータと考えていますが、動作確認では判断できなかったため、質問させていただきました。
